### ISSUE TITLE
不能判断出是否为opera浏览器，建议修改代码。

### ISSUE THREAD

**Issue by swordspringsnow** [yunnysunny/browser.js#2]
if (window.navigator.vendor && window.navigator.vendor.indexOf('Opera') == 0) {//opera
            return 'opera';
        }
可以修改为
	var userAgent = navigator.userAgent; //取得浏览器的userAgent字符串
	var isOpera = ( userAgent.indexOf("Opera") > -1 || userAgent.indexOf("OPR") > -1 ) ;
	if (isOpera) {
		return 'opera';
	};

**Comment by yunnysunny** [comment]
`userAgent.indexOf("OPR")` 这个误判的概率比较大。
`userAgent.indexOf(' OPR/')` 会好一些吧。

**Comment by yunnysunny** [comment]
代码已经更新
